### ISSUE TITLE
Repair issue when opening the file in Microsoft Powerpoint 2010

### ISSUE THREAD

**Issue by nitishkh** [PHPOffice/PHPPresentation#310]
Hi Guys,

I'm getting an issue when opening the file in powerpoint 2010 and writing it back to 2007. I have applied a image background in all 3 of my slides. It says "This image currently cannot be displayed" when I open the written file. My png turns to a jpg file as well. I have attached the ppt files below:

[sample.pptx](https://github.com/PHPOffice/PHPPresentation/files/704190/sample.pptx)
[TriviaJointSlides.pptx](https://github.com/PHPOffice/PHPPresentation/files/704191/TriviaJointSlides.pptx)

Here is my simple code:

require_once 'vendor/autoload.php';
include_once 'Sample_Header.php';

use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\Slide;
use PhpOffice\PhpPresentation\Shape\RichText;

$pptReader = IOFactory::createReader('PowerPoint2007');
$oPHPPresentation = $pptReader->load('TriviaJointSlides.pptx');

// Create slide

//$objPHPPowerPoint->addSlide();
$oTree = new PhpPptTree($oPHPPresentation);
echo $oTree->display();
if (!CLI) {
	include_once 'Sample_Footer.php';
}

$oWriterPPTX = IOFactory::createWriter($oPHPPresentation, 'PowerPoint2007');
$oWriterPPTX->save(__DIR__ . "/sample.pptx");

**Comment by Progi1984** [comment]
@nitishkh Have you got the problem with the latest version of develop branch ?

**Comment by nitishkh** [comment]
Thanks for the reply Progi1984. Yes I'm using the latest develop branch files. The repair issue keeps coming out as I open the newly generated powerpoint. I have attached my ppt files above and my codes seem to be fine.

**Comment by nitishkh** [comment]
I'm adding a bounty of $10 to whoever can help us solve this issue. 

Cheers

**Comment by abhikakade** [comment]
I also facing similar issues, with the sample code of Sample_01_simple.php. I am also using latest version of phppresentation i.e. as per composer 0.7.0 (but version file inside package says 0.6.0). I tried it with office 2010 and 2013 getting repair error mentioned above. Appreciated any help on this.

**Comment by abhikakade** [comment]
Similar issue in Office 2016, generated PPT is not opening at all even after clicking on repair option :(

**Comment by abhikakade** [comment]
HI Everyone - Checked out code from DEV-Master branch again and solved this issue for me, Now PPT is opening in both MS - Office 2013 & 2016.

**Comment by diogoico** [comment]
Same problem here, even if I just generate a empty pptx it asks me to repair and then it works properly...
I'm using PHPPresentation-0.7.0 downloaded and Common-0.2.6 both downloaded manually.

**Comment by eL-Prova** [comment]
@abhikakade what was your fix? Maybe you can fix it for this repo?

**Comment by abhikakade** [comment]
The issue was with master branch .. I checked out dev branch code and that
fixed repair issue for me.

**Comment by Progi1984** [comment]
@nitishkh : Could you test with the latest version of the **develop** branch ?

**Comment by xbitres** [comment]
@Progi1984 I also just updated to the development version and it still continues giving me a error asking for a repair. This happens on Windows 365 version as well as Mac version...
